/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentsRouteImport } from './routes/talents'
import { Route as CellsRouteImport } from './routes/cells'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CellsCellIdRouteImport } from './routes/cells.$cellId'
import { Route as MembersMemberIdRouteImport } from './routes/members.$memberId'

const TalentsRoute = TalentsRouteImport.update({
  id: '/talents',
  path: '/talents',
  getParentRoute: () => rootRouteImport,
} as any)
const CellsRoute = CellsRouteImport.update({
  id: '/cells',
  path: '/cells',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CellsCellIdRoute = CellsCellIdRouteImport.update({
  id: '/cells/$cellId',
  path: '/cells/$cellId',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/cells': typeof CellsRoute
  '/talents': typeof TalentsRoute
  '/cells/$cellId': typeof CellsCellIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/cells': typeof CellsRoute
  '/talents': typeof TalentsRoute
  '/cells/$cellId': typeof CellsCellIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/cells': typeof CellsRoute
  '/talents': typeof TalentsRoute
  '/cells/$cellId': typeof CellsCellIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attendance' | '/cells' | '/talents' | '/cells/$cellId' | '/members/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attendance' | '/cells' | '/talents' | '/cells/$cellId' | '/members/$memberId'
  id: '__root__' | '/' | '/attendance' | '/cells' | '/talents' | '/cells/$cellId' | '/members/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  CellsRoute: typeof CellsRoute
  TalentsRoute: typeof TalentsRoute
  CellsCellIdRoute: typeof CellsCellIdRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talents': {
      id: '/talents'
      path: '/talents'
      fullPath: '/talents'
      preLoaderRoute: typeof TalentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cells': {
      id: '/cells'
      path: '/cells'
      fullPath: '/cells'
      preLoaderRoute: typeof CellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cells/$cellId': {
      id: '/cells/$cellId'
      path: '/cells/$cellId'
      fullPath: '/cells/$cellId'
      preLoaderRoute: typeof CellsCellIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  CellsRoute: CellsRoute,
  TalentsRoute: TalentsRoute,
  CellsCellIdRoute: CellsCellIdRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
