/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentsRouteImport } from './routes/talents'
import { Route as PastoralRouteImport } from './routes/pastoral'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as CellsRouteImport } from './routes/cells'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersNewRouteImport } from './routes/members.new'
import { Route as MembersMemberIdRouteImport } from './routes/members.$memberId'
import { Route as DepartmentsDeptIdRouteImport } from './routes/departments.$deptId'
import { Route as CellsCellIdRouteImport } from './routes/cells.$cellId'

const TalentsRoute = TalentsRouteImport.update({
  id: '/talents',
  path: '/talents',
  getParentRoute: () => rootRouteImport,
} as any)
const PastoralRoute = PastoralRouteImport.update({
  id: '/pastoral',
  path: '/pastoral',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const CellsRoute = CellsRouteImport.update({
  id: '/cells',
  path: '/cells',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersNewRoute = MembersNewRouteImport.update({
  id: '/members/new',
  path: '/members/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsDeptIdRoute = DepartmentsDeptIdRouteImport.update({
  id: '/$deptId',
  path: '/$deptId',
  getParentRoute: () => DepartmentsRoute,
} as any)
const CellsCellIdRoute = CellsCellIdRouteImport.update({
  id: '/$cellId',
  path: '/$cellId',
  getParentRoute: () => CellsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/cells': typeof CellsRouteWithChildren
  '/departments': typeof DepartmentsRouteWithChildren
  '/pastoral': typeof PastoralRoute
  '/talents': typeof TalentsRoute
  '/cells/$cellId': typeof CellsCellIdRoute
  '/departments/$deptId': typeof DepartmentsDeptIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/new': typeof MembersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/cells': typeof CellsRouteWithChildren
  '/departments': typeof DepartmentsRouteWithChildren
  '/pastoral': typeof PastoralRoute
  '/talents': typeof TalentsRoute
  '/cells/$cellId': typeof CellsCellIdRoute
  '/departments/$deptId': typeof DepartmentsDeptIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/new': typeof MembersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/cells': typeof CellsRouteWithChildren
  '/departments': typeof DepartmentsRouteWithChildren
  '/pastoral': typeof PastoralRoute
  '/talents': typeof TalentsRoute
  '/cells/$cellId': typeof CellsCellIdRoute
  '/departments/$deptId': typeof DepartmentsDeptIdRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/new': typeof MembersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/auth'
    | '/cells'
    | '/departments'
    | '/pastoral'
    | '/talents'
    | '/cells/$cellId'
    | '/departments/$deptId'
    | '/members/$memberId'
    | '/members/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/auth'
    | '/cells'
    | '/departments'
    | '/pastoral'
    | '/talents'
    | '/cells/$cellId'
    | '/departments/$deptId'
    | '/members/$memberId'
    | '/members/new'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/auth'
    | '/cells'
    | '/departments'
    | '/pastoral'
    | '/talents'
    | '/cells/$cellId'
    | '/departments/$deptId'
    | '/members/$memberId'
    | '/members/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  CellsRoute: typeof CellsRouteWithChildren
  DepartmentsRoute: typeof DepartmentsRouteWithChildren
  PastoralRoute: typeof PastoralRoute
  TalentsRoute: typeof TalentsRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  MembersNewRoute: typeof MembersNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talents': {
      id: '/talents'
      path: '/talents'
      fullPath: '/talents'
      preLoaderRoute: typeof TalentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pastoral': {
      id: '/pastoral'
      path: '/pastoral'
      fullPath: '/pastoral'
      preLoaderRoute: typeof PastoralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cells': {
      id: '/cells'
      path: '/cells'
      fullPath: '/cells'
      preLoaderRoute: typeof CellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/new': {
      id: '/members/new'
      path: '/members/new'
      fullPath: '/members/new'
      preLoaderRoute: typeof MembersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$deptId': {
      id: '/departments/$deptId'
      path: '/$deptId'
      fullPath: '/departments/$deptId'
      preLoaderRoute: typeof DepartmentsDeptIdRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/cells/$cellId': {
      id: '/cells/$cellId'
      path: '/$cellId'
      fullPath: '/cells/$cellId'
      preLoaderRoute: typeof CellsCellIdRouteImport
      parentRoute: typeof CellsRoute
    }
  }
}

interface CellsRouteChildren {
  CellsCellIdRoute: typeof CellsCellIdRoute
}

const CellsRouteChildren: CellsRouteChildren = {
  CellsCellIdRoute: CellsCellIdRoute,
}

const CellsRouteWithChildren = CellsRoute._addFileChildren(CellsRouteChildren)

interface DepartmentsRouteChildren {
  DepartmentsDeptIdRoute: typeof DepartmentsDeptIdRoute
}

const DepartmentsRouteChildren: DepartmentsRouteChildren = {
  DepartmentsDeptIdRoute: DepartmentsDeptIdRoute,
}

const DepartmentsRouteWithChildren = DepartmentsRoute._addFileChildren(
  DepartmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  CellsRoute: CellsRouteWithChildren,
  DepartmentsRoute: DepartmentsRouteWithChildren,
  PastoralRoute: PastoralRoute,
  TalentsRoute: TalentsRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  MembersNewRoute: MembersNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
